---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 1m30s
  timeout: 15s
  dependsOn:
  - name: flux-system
    namespace: flux-system
  path: ./intermission/synology
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
