apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ex2
resources:
- ingress.yaml
- gitrepo.yaml
- imagerepo.yaml
- imagepolicy.yaml
- imageupdate.yaml
- flux-system-gitrepo.yaml
- github.com/kingdonb/podinfo//deploy/overlays/staging?ref=master
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: staging
images:
- name: img.hephy.pro/podinfo/releases
  newName: img.hephy.pro/podinfo/releases # {"$imagepolicy": "ex2:stg-policy:name"}
  newTag: 6.1.1 # {"$imagepolicy": "ex2:stg-policy:tag"}
