---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo-gha-demo
  namespace: ex3
spec:
  interval: 15s
  ref:
    branch: master
  url: https://github.com/kingdonb/podinfo
