apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  #suspend: false
  interval: 2m0s
  retryInterval: 10s
  timeout: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  path: ./secrets/lima-k8s
  prune: false
  wait: true
