apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-ex1
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  timeout: 1m
  dependsOn:
  - name: nginx
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/ex1
  prune: true
  wait: true
