---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ex1
  namespace: ex1
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/yebyen/gha-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex1
  namespace: ex1
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 2m0s
  timeout: 15s
  dependsOn:
    - name: flux-system
      namespace: flux-system
  path: ./apps/podinfo/ex01-naive-dev-automation
  prune: true
  serviceAccountName: ex1
  sourceRef:
    kind: GitRepository
    name: ex1
