apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ex7-writable
  namespace: ex7
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/kingdonb/github-actions-demo
  secretRef:
    name: ex7-writer
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ex7
  namespace: ex7
spec:
  suspend: false
  interval: 1m0s
  timeout: 15s
  dependsOn:
  - name: flux-system
    namespace: flux-system
  path: ./apps/podinfo/ex07-helmrelease-from-gitrepo-with-gitspec
  postBuild:
    substitute:
      SEMVER_TAG: 6.1.2 # {"$imagepolicy": "ex7:latest-release:tag"}
  prune: true
  serviceAccountName: ex7
  sourceRef:
    kind: GitRepository
    name: ex7-writable
