---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 3m0s
  timeout: 2m0s
  path: ./apps/ingress-nginx
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: ingress-ingress-nginx-admission
    - apiVersion: apps/v1
      kind: DaemonSet
      name: ingress-ingress-nginx-controller
      namespace: ingress-nginx
