apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  summary: kind-kind Local DEV
  exclusionList:
    - '^Dependencies do not meet ready condition, retrying in \d+s$'
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'

    - kind: GitRepository
      namespace: synology-csi
      name: '*'
    - kind: Kustomization
      namespace: synology-csi
      name: '*'
    - kind: HelmRelease
      namespace: default
      name: '*'

    - kind: GitRepository
      namespace: ex1
      name: '*'
    - kind: Kustomization
      namespace: ex1
      name: '*'
    - kind: HelmRelease
      namespace: ex1
      name: '*'

    - kind: GitRepository
      namespace: podinfo
      name: '*'
    - kind: Kustomization
      namespace: podinfo
      name: '*'
    - kind: HelmRelease
      namespace: podinfo
      name: '*'
