---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pv-demo-wordpress
  namespace: synology-csi
spec:
  interval: 1m0s
  path: ./pv-demo
  prune: true
  wait: true
  serviceAccountName: flux-sa
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: synology-csi
  dependsOn:
    - name: synology-csi-driver
