---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 1m0s
  ref:
    branch: kingdonb
  url: https://github.com/kingdonb/synology-csi
