---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi-snapshotter
  namespace: synology-csi
spec:
  interval: 1m0s
  path: ./deploy/external-snapshotter
  prune: false
  wait: true
  serviceAccountName: flux-sa
  sourceRef:
    kind: GitRepository
    name: synology-csi
