---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi-driver
  namespace: synology-csi
spec:
  interval: 5m0s
  path: ./deploy/kubernetes/v1.23
  prune: false
  wait: true
  serviceAccountName: flux-sa
  sourceRef:
    kind: GitRepository
    name: synology-csi
  dependsOn:
    - name: synology-csi-snapshotter
  patches:
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: all
    target:
      kind: Namespace
      name: synology-csi
