---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/helm-git
  prune: true
  dependsOn:
  - name: nginx
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: podinfo
