---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: minio
  namespace: minio-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kingdonb/github-actions-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio
  namespace: minio-system
spec:
  suspend: true
  interval: 1m0s
  timeout: 15s
  dependsOn:
    - name: flux-system
      namespace: flux-system
  path: ./intermission/minio
  prune: true
  serviceAccountName: minio-flux
  sourceRef:
    kind: GitRepository
    name: minio

