---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  targetNamespace: minio-system
  storageNamespace: minio-system
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
  interval: 1m0s
